import enum


class SupportedDatabaseBackend(enum.Enum):

    MARIADB = enum.auto()
    SQLITE = enum.auto()


HTTP_HEADER_RESPONSE_VERSION = "x-imagemuck-version"

HTTP_HEADER_RESPONSE_DIGEST = "Digest"

ENV_CONF_DB_BACKEND = "IMGMONK_DATABASE_BACKEND"

ENV_CONF_DB_SQLITE_PATH = "IMGMONK_SQLITE_PATH"

ENV_CONF_DB_SQLITE_PRAGMAS = "IMGMONK_SQLITE_PRAGMAS"

ENV_CONF_DB_MARIA_HOSTNAME = "IMGMONK_MARIA_HOSTNAME"

ENV_CONF_DB_MARIA_USERNAME = "IMGMONK_MARIA_USERNAME"

ENV_CONF_DB_MARIA_PASSWORD = "IMGMONK_MARIA_PASSWORD"

ENV_CONF_DB_MARIA_PORT = "IMGMONK_MARIA_PORT"

ENV_CONF_DB_MARIA_SCHEMA = "IMGMONK_MARIA_SCHEMA"

ENV_CONF_FS_STORAGE_PATH = "IMGMONK_STORAGE_PATH"

ENV_CONF_FS_UPLOAD_MAX_SIZE = "IMGMONK_UPLOAD_LIMIT"

ENV_CONF_FS_UPLOAD_FORMATS = "IMGMONK_UPLOAD_FORMATS"
